
/* Text include file generated by Toolmaker V1.13 */

#define WINDOWTEXT_CAPTUREM	"MIDI Capture"
#define MENUTEXT_PROJECT	"Project"
#define ITEMTEXT_CLEAR	"Clear"
#define ITEMTEXT_LOAD	"Load..."
#define ITEMTEXT_SAVE	"Save..."
#define ITEMTEXT_ABOUT	"About..."
#define ITEMTEXT_QUIT	"Quit"
#define MENUTEXT_SETTINGS	"Settings"
#define ITEMTEXT_SETOUTPU	"Set Output Link..."
#define ITEMTEXT_SETINPUT	"Set Input Link..."
#define GADGETTEXT_CLEAR	"Clear"
#define GADGETTEXT_SEND	"Send"
#define GADGETTEXT_SAVE	"Save..."
#define GADGETTEXT_LOAD	"Load..."
#define GADGETTEXT_BYTESINB	"Bytes in Buffer"

